import type { Metadata } from "next";
import PlusJakartaSans from "next/font/local"
import "./globals.css";

const jakartaSans = PlusJakartaSans({
  src: "./fonts/PlusJakartaSans.ttf",
  variable: "--font-jakarta-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jakartaSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
